autoforce/autoforce/urls.py
from django.conf.urls import include, patterns, url
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


from django.contrib.auth.views import login, logout

#from filebrowser.sites import site

from .views import AutoforceAuthenticationForm
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', TemplateView.as_view(template_name='index.html'),name='autoforce-home'),
                       url(r'^data/',include('data.urls',namespace='data')),
                       url(r'^workflow/',include('workflow.urls',namespace='workflow')),
                       url(r'^report/',include('report.urls',namespace='report')),
                       url(r'^admin/', include(admin.site.urls)),
                       #url(r'^login/$',AutoforceAuthenticationForm.as_view(),name='autoforce-authentication'),
                       url(r'^accounts/login/$',login, name='accounts-login'),
                       url(r'^accounts/logout/$',logout, name='accounts-logout'),
                       #url(r'^accounts/profile/$',profile,name='accounts-profile'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autoforce/cdna/urls.py
from django.conf.urls import include, patterns, url

from .views import CDNADetailView, CDNAListView

urlpatterns=patterns('',
                     url(r'^$',CDNAListView.as_view(),name='cdna-list'),
                     url(r'^(?P<cdna_pk>\d+)/$',CDNADetailView.as_view(),name='cdna-detail'),
                     )

autoforce/data/urls.py
from django.conf.urls import include, patterns, url

from .views import DataTemplateView

urlpatterns=patterns('',
                     url(r'^$',DataTemplateView.as_view(),name='data'),
                     url(r'^taxonomy/',include('taxonomy.urls',namespace='taxonomy')),
                     url(r'^reagent/',include('reagent.urls',namespace='reagent')),
                     url(r'^family/',include('family.urls',namespace='family')),
                     url(r'^experiment/',include('experiment.urls',namespace='experiment')),
                     url(r'^researcher/',include('researcher.urls',namespace='researcher')),
                     url(r'^stock/',include('stock.urls',namespace='stock')),
                     url(r'^patient/',include('patient.urls',namespace='patient')),
                     )

autoforce/report/urls.py
from django.conf.urls import include, patterns, url

from .views import ReportListView, ReportDetailView

urlpatterns=patterns('',
                     url(r'^$',ReportListView.as_view(),name='report-list'),
                     url(r'^(?P<report_pk>\d+)/$',ReportDetailView.as_view(),name='report-detail'),
                     #url(r'/humangenes/',include('humangenes.urls',namespace='humangenes')),
)

autoforce/workflow/urls.py
from django.conf.urls import include, patterns, url

from .views import WorkflowListView, WorkflowDetailView

urlpatterns=patterns('',
                     url(r'^$',WorkflowListView.as_view(),name='workflow-list'),
                     url(r'^(?P<workflow_pk>\d+)/$',WorkflowDetailView.as_view(),name='workflow-detail'),
                     #url(r'/humangenes/',include('humangenes.urls',namespace='humangenes')),
)

autoforce/autoforce/views.py
from django.contrib.auth.forms import AdminPasswordChangeForm, AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm, UserChangeForm, UserCreationForm


class AutoforceAuthenticationForm(AuthenticationForm):
    pass

autoforce/autoforce/templates/base.html
<!DOCTYPE html>
{% load bootstrap_toolkit %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>AutoForce</title>
    {% bootstrap_stylesheet_tag %}
    <style type="text/css">
      html { height: 100%; }
      body { padding-top: 60px;
      padding-bottom: 40px;
      height: 100%; }

      #wrap {
      min-height: 100%;
      height: auto !important;
      height: 100%;
      /* Negative indent footer by it's height */
      margin: 0 auto -150px;
      }

      #push,
      #footer {
      height: 10px;
      }
      #footer {
      background-color: #f5f5f5;
      }

    </style>
    <script src="http://code.jquery.com/jquery.js"></script>

    <!--  <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
	  <style>
	    body {
	    font-family: 'Yanone Kaffeesatz';
	    font-style: normal;
	    font-weight: 400;
	    font-size: 48px;
	    }
	  </style> -->
    {% bootstrap_javascript_tag %}
    {% block extra_head %}{% endblock extra_head %}
  </head>

  <body>
    <div id="wrap">
      <div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
	  <div class="container-fluid">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#">AutoForce</a>
            <div class="nav-collapse collapse">
              <p class="navbar-text pull-right">
{#		<p><a href="{% url 'autoforce-authentication' %}">Login</a><p>#}
		Logged in as <a href="{% url 'accounts-login' %}" class="navbar-link">{{ user }}</a>
              </p>
              <ul class="nav">
		<li class="active"><a href="/">Home</a></li>
		<li><a href="#about">About</a></li>
		<li><a href="#contact">Contact</a></li>
              </ul>
            </div><!--/.nav-collapse -->	
	  </div><!--/.container -->
	</div><!--/.navbar-inner -->
      </div><!--/.navbar -->
      

      {% block heading %}{% endblock heading %}

      {% bootstrap_messages %}
      <div class="container-fluid">
	<div class="row-fluid">
	  {% include "sidebar.html" %}
	  
	  <div class="span10">
	    {% block content %}{% endblock content %}
	    
	  </div>
	  
	</div><!--/.row-fluid-->
      </div><!--/.container-fluid-->

      <div id="push"></div>
    </div><!--/.wrap -->
<!--    <div id="footer">
      <div class="container">
	<p class="muted credit"><a target="_blank" href="http://www.cellbio.duke.edu/CHDM/Home.html">&copy CHDM</a> | 2013</p>
      </div>
    </div>-->
  </body>
</html>

autoforce/autoforce/templates/index.html
{% extends "base.html" %}

{% block heading %}

<div class="well text-center">
  <h1>CHDM<p>AutoForce</h1>
  <p>Automating TaskForce Administration</p>
  <p><a class="btn btn-primary" target="_blank" href="https://bitbucket.org/jeremiahsavage_duke/autoforce3/src">Check it out on BitBucket &raquo;</a></p>
</div>

{% endblock heading %}

{% block content %}
<h2>Home</h2>
{% endblock content %}

autoforce/autoforce/templates/sidebar.html
<div class="span2">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Task</li>
      <li><a href="{% url 'data:data' %}">Data</a></li>
      <li><a href="{% url 'workflow:workflow-list' %}">Workflow</a></li>
      <li><a href="{% url 'report:report-list' %}">Report</a></li>
    </ul>
  </div><!--/.well-->
</div><!--/.span2-->